// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/go-spring/stdlib/errutil"
	"github.com/go-spring/stdlib/hashutil"
	"github.com/go-spring/stdlib/httpsvr"
	"github.com/go-spring/stdlib/jsonflow"
)

var _ = strings.Index
var _ = strconv.FormatInt
var _ = http.StatusNotFound
var _ = (*httpsvr.Router)(nil)

type PayloadType int32

const (
	PayloadType_PayloadOf1 PayloadType = 1
	PayloadType_PayloadOf2 PayloadType = 2
	PayloadType_PayloadOf3 PayloadType = 3
)

var (
	PayloadType_name = map[PayloadType]string{
		1: "PayloadOf1",
		2: "PayloadOf2",
		3: "PayloadOf3",
	}
	PayloadType_value = map[string]PayloadType{
		"PayloadOf1": 1,
		"PayloadOf2": 2,
		"PayloadOf3": 3,
	}
)

// OneOfPayloadType reports whether it's a valid PayloadType.
func OneOfPayloadType(i PayloadType) bool {
	_, ok := PayloadType_name[i]
	return ok
}

// OneOfPayloadTypeAsString reports whether it's a valid PayloadTypeAsString.
func OneOfPayloadTypeAsString(i PayloadTypeAsString) bool {
	_, ok := PayloadType_name[PayloadType(i)]
	return ok
}

// PayloadTypeAsString wraps PayloadType to encode/decode as a JSON string.
type PayloadTypeAsString PayloadType

// MarshalJSON encodes the enum value as its string name.
func (x PayloadTypeAsString) MarshalJSON() ([]byte, error) {
	if s, ok := PayloadType_name[PayloadType(x)]; ok {
		return []byte(fmt.Sprintf("\"%s\"", s)), nil
	}
	return nil, errutil.Explain(nil, "invalid PayloadTypeAsString: %d", x)
}

// UnmarshalJSON decodes the enum value from its string name.
func (x *PayloadTypeAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := PayloadType_value[str]; ok {
		*x = PayloadTypeAsString(v)
		return nil
	}
	return errutil.Explain(nil, "invalid PayloadTypeAsString value: %q", str)
}

type AssistantReq struct {
	AssistantReqBody
}

// NewAssistantReq creates a new AssistantReq instance
// and initializes fields with default values.
func NewAssistantReq() *AssistantReq {
	return &AssistantReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *AssistantReq) QueryForm() (string, error) {
	return "", nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *AssistantReq) Bind(r *http.Request) (err error) {
	return
}

// Validate validates both bound parameters and request body fields.
func (x *AssistantReq) Validate() (err error) {
	if validateErr := x.AssistantReqBody.Validate(); validateErr != nil {
		err = errutil.Stack(err, "validate failed on \"AssistantReq\": %w", validateErr)
	}
	return
}

// AssistantReqBody represents the request body payload,
// excluding path and query parameters.
type AssistantReqBody struct {
	Items []*Item `json:"items,omitempty" form:"items"`
}

// NewAssistantReqBody creates a new AssistantReqBody instance
// and initializes fields with default values.
func NewAssistantReqBody() *AssistantReqBody {
	return &AssistantReqBody{}
}

// EncodeForm encodes the request body as application/x-www-form-urlencoded data.
func (x *AssistantReqBody) EncodeForm() (string, error) {
	m := make(url.Values)
	for i := range len(x.Items) {
		if x.Items[i] != nil {
			b, err := jsonflow.Marshal(*x.Items[i])
			if err != nil {
				return "", err
			}
			m.Add("items", string(b))
		}
	}
	return m.Encode(), nil
}

// DecodeForm decodes application/x-www-form-urlencoded data into the request body.
func (x *AssistantReqBody) DecodeForm(b []byte) (err error) {
	values, parseErr := url.ParseQuery(string(b))
	if parseErr != nil {
		err = errutil.Explain(err, "parse query error: %w", parseErr)
		return
	}

	if v, ok := values["items"]; ok {
		for _, s := range v {
			var i *Item
			if parseErr = jsonflow.Unmarshal([]byte(s), &i); parseErr != nil {
				err = errutil.Stack(err, "json decode error: %w", parseErr)
			} else {
				x.Items = append(x.Items, i)
			}
		}
	}

	return
}

// Validate checks field values using generated validation expressions.
func (x *AssistantReqBody) Validate() (err error) {
	return
}

type Item struct {
	Id *string `json:"id,omitempty" form:"id"`
}

// NewItem creates a new Item instance
// and initializes fields with default values.
func NewItem() *Item {
	return &Item{}
}

// DecodeJSON decodes a JSON object into Item using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *Item) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashId = 0x8b72e07b55c3ac0 // HashKey("id")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashId:
			if r.Id, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

type AssistantResp struct {
	Id      *string  `json:"id,omitempty" form:"id"`
	Data    *string  `json:"data,omitempty" form:"data"`
	Payload *Payload `json:"payload,omitempty" form:"payload"`
	Image   []byte   `json:"image,omitempty" form:"image"`
}

// NewAssistantResp creates a new AssistantResp instance
// and initializes fields with default values.
func NewAssistantResp() *AssistantResp {
	return &AssistantResp{}
}

// DecodeJSON decodes a JSON object into AssistantResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *AssistantResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashId      = 0x8b72e07b55c3ac0  // HashKey("id")
		hashData    = 0x855b556730a34a05 // HashKey("data")
		hashPayload = 0xcfb8a9d063b5e9e5 // HashKey("payload")
		hashImage   = 0x2ab612888528489a // HashKey("image")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashId:
			if r.Id, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashData:
			if r.Data, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashPayload:
			if r.Payload, err = jsonflow.DecodeObject(NewPayload)(d); err != nil {
				return err
			}
		case hashImage:
			if r.Image, err = jsonflow.DecodeBytes(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

type Payload struct {
	FieldType  PayloadTypeAsString `json:"FieldType" form:"FieldType" validate:"required"`
	PayloadOf1 *PayloadOf1         `json:"PayloadOf1,omitempty" form:"PayloadOf1"`
	PayloadOf2 *PayloadOf2         `json:"PayloadOf2,omitempty" form:"PayloadOf2"`
	PayloadOf3 *PayloadOf3         `json:"PayloadOf3,omitempty" form:"PayloadOf3"`
}

// NewPayload creates a new Payload instance
// and initializes fields with default values.
func NewPayload() *Payload {
	return &Payload{}
}

// DecodeJSON decodes a JSON object into Payload using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *Payload) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashFieldType  = 0x924fb655ccf9c75f // HashKey("FieldType")
		hashPayloadOf1 = 0xbf1a330ab6dde99b // HashKey("PayloadOf1")
		hashPayloadOf2 = 0xbf1a340ab6ddeb4e // HashKey("PayloadOf2")
		hashPayloadOf3 = 0xbf1a350ab6dded01 // HashKey("PayloadOf3")
	)

	var (
		hasFieldType bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashFieldType:
			hasFieldType = true
			if r.FieldType, err = jsonflow.DecodeAny[PayloadTypeAsString](d); err != nil {
				return err
			}
		case hashPayloadOf1:
			if r.PayloadOf1, err = jsonflow.DecodeObject(NewPayloadOf1)(d); err != nil {
				return err
			}
		case hashPayloadOf2:
			if r.PayloadOf2, err = jsonflow.DecodeObject(NewPayloadOf2)(d); err != nil {
				return err
			}
		case hashPayloadOf3:
			if r.PayloadOf3, err = jsonflow.DecodeObject(NewPayloadOf3)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasFieldType {
		err = errutil.Stack(err, "missing required field \"FieldType\"")
	}
	return
}

type PayloadOf1 struct {
}

// NewPayloadOf1 creates a new PayloadOf1 instance
// and initializes fields with default values.
func NewPayloadOf1() *PayloadOf1 {
	return &PayloadOf1{}
}

// DecodeJSON decodes a JSON object into PayloadOf1 using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *PayloadOf1) DecodeJSON(d jsonflow.Decoder) (err error) {

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

type PayloadOf2 struct {
}

// NewPayloadOf2 creates a new PayloadOf2 instance
// and initializes fields with default values.
func NewPayloadOf2() *PayloadOf2 {
	return &PayloadOf2{}
}

// DecodeJSON decodes a JSON object into PayloadOf2 using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *PayloadOf2) DecodeJSON(d jsonflow.Decoder) (err error) {

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

type PayloadOf3 struct {
}

// NewPayloadOf3 creates a new PayloadOf3 instance
// and initializes fields with default values.
func NewPayloadOf3() *PayloadOf3 {
	return &PayloadOf3{}
}

// DecodeJSON decodes a JSON object into PayloadOf3 using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *PayloadOf3) DecodeJSON(d jsonflow.Decoder) (err error) {

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}
