// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/go-spring/stdlib/errutil"
	"github.com/go-spring/stdlib/formutil"
	"github.com/go-spring/stdlib/hashutil"
	"github.com/go-spring/stdlib/httpsvr"
	"github.com/go-spring/stdlib/jsonflow"
)

var _ = strings.Index
var _ = strconv.FormatInt
var _ = formutil.EncodeInt
var _ = base64.StdEncoding
var _ = http.StatusNotFound
var _ = (*httpsvr.Router)(nil)

// years
const MAX_AGE int64 = 150

const MIN_AGE int64 = 18

const DEFAULT_VIP bool = false

const DEFAULT_ROLE string = "user"

const DEFAULT_PAGE int64 = 1

const DEFAULT_PAGE_SIZE int64 = 20

const MAX_PAGE_SIZE int64 = 100

const SALARY_MIN float64 = 0.0

const SALARY_MAX float64 = 1000000.0

// Standard error codes
type ErrCode int32

const (
	ErrCode_ERR_OK            ErrCode = 0
	ErrCode_PARAM_ERROR       ErrCode = 1003
	ErrCode_NOT_FOUND         ErrCode = 4004
	ErrCode_PERMISSION_DENIED ErrCode = 4003
	ErrCode_INTERNAL_ERROR    ErrCode = 5000
)

var (
	ErrCode_name = map[ErrCode]string{
		0:    "ERR_OK",
		1003: "PARAM_ERROR",
		4004: "NOT_FOUND",
		4003: "PERMISSION_DENIED",
		5000: "INTERNAL_ERROR",
	}
	ErrCode_value = map[string]ErrCode{
		"ERR_OK":            0,
		"PARAM_ERROR":       1003,
		"NOT_FOUND":         4004,
		"PERMISSION_DENIED": 4003,
		"INTERNAL_ERROR":    5000,
	}
	ErrCode_message = map[ErrCode]string{
		0:    "ERR_OK",
		1003: "param error",
		4004: "NOT_FOUND",
		4003: "PERMISSION_DENIED",
		5000: "INTERNAL_ERROR",
	}
)

// OneOfErrCode reports whether it's a valid ErrCode.
func OneOfErrCode(i ErrCode) bool {
	_, ok := ErrCode_name[i]
	return ok
}

// OneOfErrCodeAsString reports whether it's a valid ErrCodeAsString.
func OneOfErrCodeAsString(i ErrCodeAsString) bool {
	_, ok := ErrCode_name[ErrCode(i)]
	return ok
}

// ErrCodeAsString wraps ErrCode to encode/decode as a JSON string.
type ErrCodeAsString ErrCode

// MarshalJSON encodes the enum value as its string name.
func (x ErrCodeAsString) MarshalJSON() ([]byte, error) {
	if s, ok := ErrCode_name[ErrCode(x)]; ok {
		return []byte(fmt.Sprintf("\"%s\"", s)), nil
	}
	return nil, errutil.Explain(nil, "invalid ErrCodeAsString: %d", x)
}

// UnmarshalJSON decodes the enum value from its string name.
func (x *ErrCodeAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := ErrCode_value[str]; ok {
		*x = ErrCodeAsString(v)
		return nil
	}
	return errutil.Explain(nil, "invalid ErrCodeAsString value: %q", str)
}

// Manager seniority levels
type ManagerLevel int32

const (
	ManagerLevel_JUNIOR ManagerLevel = 1
	ManagerLevel_MIDDLE ManagerLevel = 2
	ManagerLevel_SENIOR ManagerLevel = 3
)

var (
	ManagerLevel_name = map[ManagerLevel]string{
		1: "JUNIOR",
		2: "MIDDLE",
		3: "SENIOR",
	}
	ManagerLevel_value = map[string]ManagerLevel{
		"JUNIOR": 1,
		"MIDDLE": 2,
		"SENIOR": 3,
	}
)

// OneOfManagerLevel reports whether it's a valid ManagerLevel.
func OneOfManagerLevel(i ManagerLevel) bool {
	_, ok := ManagerLevel_name[i]
	return ok
}

// OneOfManagerLevelAsString reports whether it's a valid ManagerLevelAsString.
func OneOfManagerLevelAsString(i ManagerLevelAsString) bool {
	_, ok := ManagerLevel_name[ManagerLevel(i)]
	return ok
}

// ManagerLevelAsString wraps ManagerLevel to encode/decode as a JSON string.
type ManagerLevelAsString ManagerLevel

// MarshalJSON encodes the enum value as its string name.
func (x ManagerLevelAsString) MarshalJSON() ([]byte, error) {
	if s, ok := ManagerLevel_name[ManagerLevel(x)]; ok {
		return []byte(fmt.Sprintf("\"%s\"", s)), nil
	}
	return nil, errutil.Explain(nil, "invalid ManagerLevelAsString: %d", x)
}

// UnmarshalJSON decodes the enum value from its string name.
func (x *ManagerLevelAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := ManagerLevel_value[str]; ok {
		*x = ManagerLevelAsString(v)
		return nil
	}
	return errutil.Explain(nil, "invalid ManagerLevelAsString value: %q", str)
}

// Company departments
type Department int32

const (
	Department_ENGINEERING Department = 1
	Department_MARKETING   Department = 2
	Department_SALES       Department = 3
	Department_HR          Department = 4
	Department_FINANCE     Department = 5
)

var (
	Department_name = map[Department]string{
		1: "ENGINEERING",
		2: "MARKETING",
		3: "SALES",
		4: "HR",
		5: "FINANCE",
	}
	Department_value = map[string]Department{
		"ENGINEERING": 1,
		"MARKETING":   2,
		"SALES":       3,
		"HR":          4,
		"FINANCE":     5,
	}
)

// OneOfDepartment reports whether it's a valid Department.
func OneOfDepartment(i Department) bool {
	_, ok := Department_name[i]
	return ok
}

// OneOfDepartmentAsString reports whether it's a valid DepartmentAsString.
func OneOfDepartmentAsString(i DepartmentAsString) bool {
	_, ok := Department_name[Department(i)]
	return ok
}

// DepartmentAsString wraps Department to encode/decode as a JSON string.
type DepartmentAsString Department

// MarshalJSON encodes the enum value as its string name.
func (x DepartmentAsString) MarshalJSON() ([]byte, error) {
	if s, ok := Department_name[Department(x)]; ok {
		return []byte(fmt.Sprintf("\"%s\"", s)), nil
	}
	return nil, errutil.Explain(nil, "invalid DepartmentAsString: %d", x)
}

// UnmarshalJSON decodes the enum value from its string name.
func (x *DepartmentAsString) UnmarshalJSON(data []byte) error {
	str := strings.Trim(string(data), "\"")
	if v, ok := Department_value[str]; ok {
		*x = DepartmentAsString(v)
		return nil
	}
	return errutil.Explain(nil, "invalid DepartmentAsString value: %q", str)
}

// Pagination request and response
type PageReq struct {
	Page int64 `json:"page" query:"page" validate:"required"`
	Size int64 `json:"size" query:"size" validate:"required"`
}

// NewPageReq creates a new PageReq instance
// and initializes fields with default values.
func NewPageReq() *PageReq {
	return &PageReq{}
}

// DecodeJSON decodes a JSON object into PageReq using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *PageReq) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashPage = 0x38b2a0deba58916  // HashKey("page")
		hashSize = 0x4dea9618e618ae3c // HashKey("size")
	)

	var (
		hasPage bool
		hasSize bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashPage:
			hasPage = true
			if r.Page, err = jsonflow.DecodeInt[int64](d); err != nil {
				return err
			}
		case hashSize:
			hasSize = true
			if r.Size, err = jsonflow.DecodeInt[int64](d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasPage {
		return errutil.Explain(err, "missing required field \"page\"")
	}
	if !hasSize {
		return errutil.Explain(err, "missing required field \"size\"")
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *PageReq) Validate() error {
	if !(x.Page >= 1) {
		return errutil.Explain(nil, "validate failed on \"PageReq.Page\"")
	}
	if !(x.Size >= 1 && x.Size <= MAX_PAGE_SIZE) {
		return errutil.Explain(nil, "validate failed on \"PageReq.Size\"")
	}
	return nil
}

// Address & Contact info
type Address struct {
	City       *string `json:"city,omitempty" form:"city"`
	Street     *string `json:"street,omitempty" form:"street"`
	PostalCode *string `json:"postalCode,omitempty" form:"postalCode"`
}

// NewAddress creates a new Address instance
// and initializes fields with default values.
func NewAddress() *Address {
	return &Address{}
}

// DecodeJSON decodes a JSON object into Address using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *Address) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashCity       = 0xf9dab5910f08a8a2 // HashKey("city")
		hashStreet     = 0x4f5c4dd8e884633e // HashKey("street")
		hashPostalCode = 0x95dac24ad2f17db7 // HashKey("postalCode")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashCity:
			if r.City, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashStreet:
			if r.Street, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashPostalCode:
			if r.PostalCode, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

type ContactInfo struct {
	Email   string   `json:"email" form:"email" validate:"required"`
	Phone   string   `json:"phone" form:"phone" validate:"required" default:""`
	Address *Address `json:"address,omitempty" form:"address"`
}

// NewContactInfo creates a new ContactInfo instance
// and initializes fields with default values.
func NewContactInfo() *ContactInfo {
	return &ContactInfo{
		Phone: "",
	}
}

// DecodeJSON decodes a JSON object into ContactInfo using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *ContactInfo) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashEmail   = 0x123467b419acbc07 // HashKey("email")
		hashPhone   = 0x31fc9c6bde865d6f // HashKey("phone")
		hashAddress = 0x1737f69e334c12b3 // HashKey("address")
	)

	var (
		hasEmail bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashEmail:
			hasEmail = true
			if r.Email, err = jsonflow.DecodeString(d); err != nil {
				return err
			}
		case hashPhone:
			if r.Phone, err = jsonflow.DecodeString(d); err != nil {
				return err
			}
		case hashAddress:
			if r.Address, err = jsonflow.DecodeObject(NewAddress)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasEmail {
		return errutil.Explain(err, "missing required field \"email\"")
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *ContactInfo) Validate() error {
	if !(Email(x.Email)) {
		return errutil.Explain(nil, "validate failed on \"ContactInfo.Email\"")
	}
	return nil
}

// Department info
type DepartmentInfo struct {
	Dept     *Department `json:"dept,omitempty" form:"dept"`
	DeptName *string     `json:"deptName,omitempty" form:"deptName"`
}

// NewDepartmentInfo creates a new DepartmentInfo instance
// and initializes fields with default values.
func NewDepartmentInfo() *DepartmentInfo {
	return &DepartmentInfo{}
}

// DecodeJSON decodes a JSON object into DepartmentInfo using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *DepartmentInfo) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashDept     = 0xa5ef04674280b406 // HashKey("dept")
		hashDeptName = 0x63c798c819b02345 // HashKey("deptName")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashDept:
			if r.Dept, err = jsonflow.DecodeIntPtr[Department](d); err != nil {
				return err
			}
		case hashDeptName:
			if r.DeptName, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

// Manager entity definition
type Manager struct {
	Id             *string                                 `json:"id,omitempty" form:"id"`
	Name           *string                                 `json:"name,omitempty" form:"name"`
	Age            *int64                                  `json:"age,omitempty" form:"age"`
	Vip            *bool                                   `json:"vip,omitempty" form:"vip"`
	Salary         *float64                                `json:"salary,omitempty" form:"salary"`
	Role           *string                                 `json:"role,omitempty" form:"role"`
	Level          *ManagerLevelAsString                   `json:"level,omitempty" form:"level"`
	DeptInfo       *DepartmentInfo                         `json:"deptInfo,omitempty" form:"deptInfo"`
	Contact        *ContactInfo                            `json:"contact,omitempty" form:"contact"`
	ContactInfos   []*ContactInfo                          `json:"contactInfos,omitempty" form:"contactInfos"`
	ContactInfoV2s [][]*ContactInfo                        `json:"contactInfoV2s,omitempty" form:"contactInfoV2s"`
	ContactInfoV3s [][][]*ContactInfo                      `json:"contactInfoV3s,omitempty" form:"contactInfoV3s"`
	ContactMaps    map[string]*ContactInfo                 `json:"contactMaps,omitempty" form:"contactMaps"`
	ContactMapV2s  map[string][]*ContactInfo               `json:"contactMapV2s,omitempty" form:"contactMapV2s"`
	ContactMapV3s  map[string]map[int64]*ContactInfo       `json:"contactMapV3s,omitempty" form:"contactMapV3s"`
	Extra          map[string]string                       `json:"extra,omitempty" form:"extra"`
	ExtraV2        map[string]map[string]string            `json:"extraV2,omitempty" form:"extraV2"`
	ExtraV3        map[string]map[string]map[string]string `json:"extraV3,omitempty" form:"extraV3"`
	ExtraV4        map[string]map[string][]string          `json:"extraV4,omitempty" form:"extraV4"`
	ExtraV5        map[string][]string                     `json:"extraV5,omitempty" form:"extraV5"`
}

// NewManager creates a new Manager instance
// and initializes fields with default values.
func NewManager() *Manager {
	return &Manager{}
}

// DecodeJSON decodes a JSON object into Manager using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *Manager) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashId             = 0x8b72e07b55c3ac0  // HashKey("id")
		hashName           = 0xc4bcadba8e631b86 // HashKey("name")
		hashAge            = 0xe715b4190539215c // HashKey("age")
		hashVip            = 0x68e906194eba76f0 // HashKey("vip")
		hashSalary         = 0x69c724098dbd2bc3 // HashKey("salary")
		hashRole           = 0xa358ec1ff0c833b9 // HashKey("role")
		hashLevel          = 0xe8ddc90a9d7c709d // HashKey("level")
		hashDeptInfo       = 0x909196037ac21a36 // HashKey("deptInfo")
		hashContact        = 0x623617b538360a63 // HashKey("contact")
		hashContactInfos   = 0xe86fa0653a0df08c // HashKey("contactInfos")
		hashContactInfoV2s = 0xd0c2fecd180f9960 // HashKey("contactInfoV2s")
		hashContactInfoV3s = 0xd0bffecd180d6389 // HashKey("contactInfoV3s")
		hashContactMaps    = 0xd342cef8b6401440 // HashKey("contactMaps")
		hashContactMapV2s  = 0xb6aa83f0e06775cc // HashKey("contactMapV2s")
		hashContactMapV3s  = 0xb6a783f0e0653ff5 // HashKey("contactMapV3s")
		hashExtra          = 0xfd29ee12a979cb69 // HashKey("extra")
		hashExtraV2        = 0x7eaf4c37ba38bf0d // HashKey("extraV2")
		hashExtraV3        = 0x7eaf4b37ba38bd5a // HashKey("extraV3")
		hashExtraV4        = 0x7eaf4637ba38b4db // HashKey("extraV4")
		hashExtraV5        = 0x7eaf4537ba38b328 // HashKey("extraV5")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashId:
			if r.Id, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashName:
			if r.Name, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashAge:
			if r.Age, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashVip:
			if r.Vip, err = jsonflow.DecodeBoolPtr(d); err != nil {
				return err
			}
		case hashSalary:
			if r.Salary, err = jsonflow.DecodeFloatPtr[float64](d); err != nil {
				return err
			}
		case hashRole:
			if r.Role, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashLevel:
			if r.Level, err = jsonflow.DecodeAny[*ManagerLevelAsString](d); err != nil {
				return err
			}
		case hashDeptInfo:
			if r.DeptInfo, err = jsonflow.DecodeObject(NewDepartmentInfo)(d); err != nil {
				return err
			}
		case hashContact:
			if r.Contact, err = jsonflow.DecodeObject(NewContactInfo)(d); err != nil {
				return err
			}
		case hashContactInfos:
			if r.ContactInfos, err = jsonflow.DecodeArray(jsonflow.DecodeObject(NewContactInfo))(d); err != nil {
				return err
			}
		case hashContactInfoV2s:
			if r.ContactInfoV2s, err = jsonflow.DecodeArray(jsonflow.DecodeArray(jsonflow.DecodeObject(NewContactInfo)))(d); err != nil {
				return err
			}
		case hashContactInfoV3s:
			if r.ContactInfoV3s, err = jsonflow.DecodeArray(jsonflow.DecodeArray(jsonflow.DecodeArray(jsonflow.DecodeObject(NewContactInfo))))(d); err != nil {
				return err
			}
		case hashContactMaps:
			if r.ContactMaps, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeObject(NewContactInfo))(d); err != nil {
				return err
			}
		case hashContactMapV2s:
			if r.ContactMapV2s, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeArray(jsonflow.DecodeObject(NewContactInfo)))(d); err != nil {
				return err
			}
		case hashContactMapV3s:
			if r.ContactMapV3s, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeMap(jsonflow.DecodeInt[int64], jsonflow.DecodeObject(NewContactInfo)))(d); err != nil {
				return err
			}
		case hashExtra:
			if r.Extra, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeString)(d); err != nil {
				return err
			}
		case hashExtraV2:
			if r.ExtraV2, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeString))(d); err != nil {
				return err
			}
		case hashExtraV3:
			if r.ExtraV3, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeString)))(d); err != nil {
				return err
			}
		case hashExtraV4:
			if r.ExtraV4, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeArray(jsonflow.DecodeString)))(d); err != nil {
				return err
			}
		case hashExtraV5:
			if r.ExtraV5, err = jsonflow.DecodeMap(jsonflow.DecodeString, jsonflow.DecodeArray(jsonflow.DecodeString))(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *Manager) Validate() error {
	if x.Name != nil {
		if !(len(*x.Name) > 0 && len(*x.Name) <= 64) {
			return errutil.Explain(nil, "validate failed on \"Manager.Name\"")
		}
	}
	if x.Age != nil {
		if !(*x.Age >= MIN_AGE && *x.Age <= MAX_AGE) {
			return errutil.Explain(nil, "validate failed on \"Manager.Age\"")
		}
	}
	if x.Salary != nil {
		if !(*x.Salary >= SALARY_MIN && *x.Salary <= SALARY_MAX) {
			return errutil.Explain(nil, "validate failed on \"Manager.Salary\"")
		}
	}
	return nil
}

// Single manager by ID
type ManagerReq struct {
	ManagerReqBody
	Id string `json:"id" path:"id" validate:"required"`
}

// NewManagerReq creates a new ManagerReq instance
// and initializes fields with default values.
func NewManagerReq() *ManagerReq {
	return &ManagerReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *ManagerReq) QueryForm() (string, error) {
	return "", nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *ManagerReq) Bind(r *http.Request) error {
	c := httpsvr.GetRequestContext(r.Context())
	if s := c.PathValue("id"); s == "" {
		return errutil.Explain(nil, "required path parameter \"id\" is missing")
	} else {
		x.Id = s
	}
	return nil
}

// Validate validates both bound parameters and request body fields.
func (x *ManagerReq) Validate() error {
	if err := x.ManagerReqBody.Validate(); err != nil {
		return errutil.Explain(err, "validate failed on \"ManagerReq\"")
	}
	return nil
}

// ManagerReqBody represents the request body payload,
// excluding path and query parameters.
type ManagerReqBody struct {
}

// NewManagerReqBody creates a new ManagerReqBody instance
// and initializes fields with default values.
func NewManagerReqBody() *ManagerReqBody {
	return &ManagerReqBody{}
}

// EncodeForm encodes the request body as application/x-www-form-urlencoded data.
func (x *ManagerReqBody) EncodeForm() (string, error) {
	return "", nil
}

// DecodeForm decodes application/x-www-form-urlencoded data into the request body.
func (x *ManagerReqBody) DecodeForm(b []byte) error {
	return nil
}

// Validate checks field values using generated validation expressions.
func (x *ManagerReqBody) Validate() error {
	return nil
}

// Create new manager
type CreateManagerReq struct {
	CreateManagerReqBody
}

// NewCreateManagerReq creates a new CreateManagerReq instance
// and initializes fields with default values.
func NewCreateManagerReq() *CreateManagerReq {
	return &CreateManagerReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *CreateManagerReq) QueryForm() (string, error) {
	return "", nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *CreateManagerReq) Bind(r *http.Request) error {
	return nil
}

// Validate validates both bound parameters and request body fields.
func (x *CreateManagerReq) Validate() error {
	if err := x.CreateManagerReqBody.Validate(); err != nil {
		return errutil.Explain(err, "validate failed on \"CreateManagerReq\"")
	}
	return nil
}

// CreateManagerReqBody represents the request body payload,
// excluding path and query parameters.
type CreateManagerReqBody struct {
	Name     *string               `json:"name,omitempty" form:"name"`
	Age      *int64                `json:"age,omitempty" form:"age"`
	Vip      *bool                 `json:"vip,omitempty" form:"vip"`
	Salary   *float64              `json:"salary,omitempty" form:"salary"`
	Role     *string               `json:"role,omitempty" form:"role"`
	Level    *ManagerLevelAsString `json:"level,omitempty" form:"level"`
	DeptInfo *DepartmentInfo       `json:"deptInfo,omitempty" form:"deptInfo"`
	Contact  *ContactInfo          `json:"contact,omitempty" form:"contact"`
}

// NewCreateManagerReqBody creates a new CreateManagerReqBody instance
// and initializes fields with default values.
func NewCreateManagerReqBody() *CreateManagerReqBody {
	return &CreateManagerReqBody{}
}

// DecodeJSON decodes a JSON object into CreateManagerReqBody using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *CreateManagerReqBody) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashName     = 0xc4bcadba8e631b86 // HashKey("name")
		hashAge      = 0xe715b4190539215c // HashKey("age")
		hashVip      = 0x68e906194eba76f0 // HashKey("vip")
		hashSalary   = 0x69c724098dbd2bc3 // HashKey("salary")
		hashRole     = 0xa358ec1ff0c833b9 // HashKey("role")
		hashLevel    = 0xe8ddc90a9d7c709d // HashKey("level")
		hashDeptInfo = 0x909196037ac21a36 // HashKey("deptInfo")
		hashContact  = 0x623617b538360a63 // HashKey("contact")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashName:
			if r.Name, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashAge:
			if r.Age, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashVip:
			if r.Vip, err = jsonflow.DecodeBoolPtr(d); err != nil {
				return err
			}
		case hashSalary:
			if r.Salary, err = jsonflow.DecodeFloatPtr[float64](d); err != nil {
				return err
			}
		case hashRole:
			if r.Role, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashLevel:
			if r.Level, err = jsonflow.DecodeAny[*ManagerLevelAsString](d); err != nil {
				return err
			}
		case hashDeptInfo:
			if r.DeptInfo, err = jsonflow.DecodeObject(NewDepartmentInfo)(d); err != nil {
				return err
			}
		case hashContact:
			if r.Contact, err = jsonflow.DecodeObject(NewContactInfo)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *CreateManagerReqBody) Validate() error {
	if x.Name != nil {
		if !(len(*x.Name) > 0 && len(*x.Name) <= 64) {
			return errutil.Explain(nil, "validate failed on \"CreateManagerReq.Name\"")
		}
	}
	if x.Age != nil {
		if !(*x.Age >= MIN_AGE && *x.Age <= MAX_AGE) {
			return errutil.Explain(nil, "validate failed on \"CreateManagerReq.Age\"")
		}
	}
	if x.Salary != nil {
		if !(*x.Salary >= SALARY_MIN && *x.Salary <= SALARY_MAX) {
			return errutil.Explain(nil, "validate failed on \"CreateManagerReq.Salary\"")
		}
	}
	if x.Contact != nil {
		if err := x.Contact.Validate(); err != nil {
			return errutil.Explain(err, "validate failed on \"CreateManagerReq.Contact\"")
		}
	}
	return nil
}

// Update existing manager
type UpdateManagerReq struct {
	UpdateManagerReqBody
	ID string `json:"id" path:"id" validate:"required"`
}

// NewUpdateManagerReq creates a new UpdateManagerReq instance
// and initializes fields with default values.
func NewUpdateManagerReq() *UpdateManagerReq {
	return &UpdateManagerReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *UpdateManagerReq) QueryForm() (string, error) {
	return "", nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *UpdateManagerReq) Bind(r *http.Request) error {
	c := httpsvr.GetRequestContext(r.Context())
	if s := c.PathValue("id"); s == "" {
		return errutil.Explain(nil, "required path parameter \"id\" is missing")
	} else {
		x.ID = s
	}
	return nil
}

// Validate validates both bound parameters and request body fields.
func (x *UpdateManagerReq) Validate() error {
	if err := x.UpdateManagerReqBody.Validate(); err != nil {
		return errutil.Explain(err, "validate failed on \"UpdateManagerReq\"")
	}
	return nil
}

// UpdateManagerReqBody represents the request body payload,
// excluding path and query parameters.
type UpdateManagerReqBody struct {
	Name     *string         `json:"name,omitempty" form:"name"`
	Age      *int64          `json:"age,omitempty" form:"age"`
	Vip      *bool           `json:"vip" form:"vip"`
	Salary   *float64        `json:"salary,omitempty" form:"salary"`
	Role     *string         `json:"role,omitempty" form:"role"`
	Level    *ManagerLevel   `json:"level,omitempty" form:"level"`
	DeptInfo *DepartmentInfo `json:"dept_info,omitempty" form:"dept_info"`
	Contact  *ContactInfo    `json:"contact,omitempty" form:"contact"`
}

// NewUpdateManagerReqBody creates a new UpdateManagerReqBody instance
// and initializes fields with default values.
func NewUpdateManagerReqBody() *UpdateManagerReqBody {
	return &UpdateManagerReqBody{}
}

// DecodeJSON decodes a JSON object into UpdateManagerReqBody using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *UpdateManagerReqBody) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashName     = 0xc4bcadba8e631b86 // HashKey("name")
		hashAge      = 0xe715b4190539215c // HashKey("age")
		hashVip      = 0x68e906194eba76f0 // HashKey("vip")
		hashSalary   = 0x69c724098dbd2bc3 // HashKey("salary")
		hashRole     = 0xa358ec1ff0c833b9 // HashKey("role")
		hashLevel    = 0xe8ddc90a9d7c709d // HashKey("level")
		hashDeptInfo = 0x1048de984afc041f // HashKey("dept_info")
		hashContact  = 0x623617b538360a63 // HashKey("contact")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashName:
			if r.Name, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashAge:
			if r.Age, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashVip:
			if r.Vip, err = jsonflow.DecodeBoolPtr(d); err != nil {
				return err
			}
		case hashSalary:
			if r.Salary, err = jsonflow.DecodeFloatPtr[float64](d); err != nil {
				return err
			}
		case hashRole:
			if r.Role, err = jsonflow.DecodeStringPtr(d); err != nil {
				return err
			}
		case hashLevel:
			if r.Level, err = jsonflow.DecodeIntPtr[ManagerLevel](d); err != nil {
				return err
			}
		case hashDeptInfo:
			if r.DeptInfo, err = jsonflow.DecodeObject(NewDepartmentInfo)(d); err != nil {
				return err
			}
		case hashContact:
			if r.Contact, err = jsonflow.DecodeObject(NewContactInfo)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *UpdateManagerReqBody) Validate() error {
	if x.Age != nil {
		if !(*x.Age >= MIN_AGE && *x.Age <= MAX_AGE) {
			return errutil.Explain(nil, "validate failed on \"UpdateManagerReq.Age\"")
		}
	}
	if x.Salary != nil {
		if !(*x.Salary >= SALARY_MIN && *x.Salary <= SALARY_MAX) {
			return errutil.Explain(nil, "validate failed on \"UpdateManagerReq.Salary\"")
		}
	}
	if x.Contact != nil {
		if err := x.Contact.Validate(); err != nil {
			return errutil.Explain(err, "validate failed on \"UpdateManagerReq.Contact\"")
		}
	}
	return nil
}

// Paginated manager query
type ListManagersByPageReq struct {
	ListManagersByPageReqBody
	Page     int64         `json:"page" query:"page" validate:"required"`
	Size     int64         `json:"size" query:"size" validate:"required"`
	Keyword  []string      `json:"keyword,omitempty" query:"keyword"`
	Dept     *Department   `json:"dept,omitempty" query:"dept"`
	MinLevel *ManagerLevel `json:"minLevel,omitempty" query:"minLevel"`
	Vip      *bool         `json:"vip,omitempty" query:"vip"`
}

// NewListManagersByPageReq creates a new ListManagersByPageReq instance
// and initializes fields with default values.
func NewListManagersByPageReq() *ListManagersByPageReq {
	return &ListManagersByPageReq{}
}

// QueryForm encodes query-bound fields into URL-encoded form data.
func (x *ListManagersByPageReq) QueryForm() (string, error) {
	form := make(url.Values)
	if err := formutil.EncodeInt(form, "page", x.Page); err != nil {
		return "", errutil.Explain(err, "encode form field \"page\" error")
	}
	if err := formutil.EncodeInt(form, "size", x.Size); err != nil {
		return "", errutil.Explain(err, "encode form field \"size\" error")
	}
	if err := formutil.EncodeList(form, "keyword", x.Keyword, formutil.EncodeString); err != nil {
		return "", errutil.Explain(err, "encode form field \"keyword\" error")
	}
	if err := formutil.EncodeIntPtr(form, "dept", x.Dept); err != nil {
		return "", errutil.Explain(err, "encode form field \"dept\" error")
	}
	if err := formutil.EncodeIntPtr(form, "minLevel", x.MinLevel); err != nil {
		return "", errutil.Explain(err, "encode form field \"minLevel\" error")
	}
	if err := formutil.EncodeBoolPtr(form, "vip", x.Vip); err != nil {
		return "", errutil.Explain(err, "encode form field \"vip\" error")
	}
	return form.Encode(), nil
}

// Bind extracts path and query parameters from the HTTP request
// and assigns them to the corresponding struct fields.
func (x *ListManagersByPageReq) Bind(r *http.Request) error {
	form, err := url.ParseQuery(r.URL.RawQuery)
	if err != nil {
		return errutil.Explain(err, "parse query error")
	}

	var (
		hasPage bool
		hasSize bool
	)

	for key, values := range form {
		if len(values) == 0 {
			continue
		}
		switch key {
		case "page":
			hasPage = true
			if x.Page, err = formutil.DecodeInt[int64](key, values); err != nil {
				return errutil.Explain(err, "decode form field \"page\" error")
			}
		case "size":
			hasSize = true
			if x.Size, err = formutil.DecodeInt[int64](key, values); err != nil {
				return errutil.Explain(err, "decode form field \"size\" error")
			}
		case "keyword":
			if x.Keyword, err = formutil.DecodeList(key, values, formutil.DecodeString); err != nil {
				return errutil.Explain(err, "decode form field \"keyword\" error")
			}
		case "dept":
			if x.Dept, err = formutil.DecodeIntPtr[Department](key, values); err != nil {
				return errutil.Explain(err, "decode form field \"dept\" error")
			}
		case "minLevel":
			if x.MinLevel, err = formutil.DecodeIntPtr[ManagerLevel](key, values); err != nil {
				return errutil.Explain(err, "decode form field \"minLevel\" error")
			}
		case "vip":
			if x.Vip, err = formutil.DecodeBoolPtr(key, values); err != nil {
				return errutil.Explain(err, "decode form field \"vip\" error")
			}
		}
	}

	if !hasPage {
		err = errutil.Explain(err, "missing required field \"page\"")
	}
	if !hasSize {
		err = errutil.Explain(err, "missing required field \"size\"")
	}
	return nil
}

// Validate validates both bound parameters and request body fields.
func (x *ListManagersByPageReq) Validate() error {
	if !(x.Page >= 1) {
		return errutil.Explain(nil, "validate failed on \"ListManagersByPageReq.Page\"")
	}
	if !(x.Size >= 1 && x.Size <= MAX_PAGE_SIZE) {
		return errutil.Explain(nil, "validate failed on \"ListManagersByPageReq.Size\"")
	}
	if !(len(x.Keyword) <= 5) {
		return errutil.Explain(nil, "validate failed on \"ListManagersByPageReq.Keyword\"")
	}
	if err := x.ListManagersByPageReqBody.Validate(); err != nil {
		return errutil.Explain(err, "validate failed on \"ListManagersByPageReq\"")
	}
	return nil
}

// ListManagersByPageReqBody represents the request body payload,
// excluding path and query parameters.
type ListManagersByPageReqBody struct {
}

// NewListManagersByPageReqBody creates a new ListManagersByPageReqBody instance
// and initializes fields with default values.
func NewListManagersByPageReqBody() *ListManagersByPageReqBody {
	return &ListManagersByPageReqBody{}
}

// EncodeForm encodes the request body as application/x-www-form-urlencoded data.
func (x *ListManagersByPageReqBody) EncodeForm() (string, error) {
	return "", nil
}

// DecodeForm decodes application/x-www-form-urlencoded data into the request body.
func (x *ListManagersByPageReqBody) DecodeForm(b []byte) error {
	return nil
}

// Validate checks field values using generated validation expressions.
func (x *ListManagersByPageReqBody) Validate() error {
	return nil
}

// Create / Update / Get responses
type CreateManagerResp struct {
	Errno  ErrCode  `json:"errno" form:"errno" validate:"required"`
	Errmsg string   `json:"errmsg" form:"errmsg" validate:"required"`
	Data   *Manager `json:"data,omitempty" form:"data"`
}

// NewCreateManagerResp creates a new CreateManagerResp instance
// and initializes fields with default values.
func NewCreateManagerResp() *CreateManagerResp {
	return &CreateManagerResp{}
}

// DecodeJSON decodes a JSON object into CreateManagerResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *CreateManagerResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashErrno  = 0x9f713ddd75d2f3ab // HashKey("errno")
		hashErrmsg = 0xb91eb24f31be5e25 // HashKey("errmsg")
		hashData   = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasErrno  bool
		hasErrmsg bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashErrno:
			hasErrno = true
			if r.Errno, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}
		case hashErrmsg:
			hasErrmsg = true
			if r.Errmsg, err = jsonflow.DecodeString(d); err != nil {
				return err
			}
		case hashData:
			if r.Data, err = jsonflow.DecodeObject(NewManager)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasErrno {
		return errutil.Explain(err, "missing required field \"errno\"")
	}
	if !hasErrmsg {
		return errutil.Explain(err, "missing required field \"errmsg\"")
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *CreateManagerResp) Validate() error {
	if !(OneOfErrCode(x.Errno)) {
		return errutil.Explain(nil, "validate failed on \"CreateManagerResp.Errno\"")
	}
	return nil
}

type UpdateManagerResp struct {
	Errno  ErrCode  `json:"errno" form:"errno" validate:"required"`
	Errmsg string   `json:"errmsg" form:"errmsg" validate:"required"`
	Data   *Manager `json:"data,omitempty" form:"data"`
}

// NewUpdateManagerResp creates a new UpdateManagerResp instance
// and initializes fields with default values.
func NewUpdateManagerResp() *UpdateManagerResp {
	return &UpdateManagerResp{}
}

// DecodeJSON decodes a JSON object into UpdateManagerResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *UpdateManagerResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashErrno  = 0x9f713ddd75d2f3ab // HashKey("errno")
		hashErrmsg = 0xb91eb24f31be5e25 // HashKey("errmsg")
		hashData   = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasErrno  bool
		hasErrmsg bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashErrno:
			hasErrno = true
			if r.Errno, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}
		case hashErrmsg:
			hasErrmsg = true
			if r.Errmsg, err = jsonflow.DecodeString(d); err != nil {
				return err
			}
		case hashData:
			if r.Data, err = jsonflow.DecodeObject(NewManager)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasErrno {
		return errutil.Explain(err, "missing required field \"errno\"")
	}
	if !hasErrmsg {
		return errutil.Explain(err, "missing required field \"errmsg\"")
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *UpdateManagerResp) Validate() error {
	if !(OneOfErrCode(x.Errno)) {
		return errutil.Explain(nil, "validate failed on \"UpdateManagerResp.Errno\"")
	}
	return nil
}

type GetManagerResp struct {
	Errno  ErrCode  `json:"errno" form:"errno" validate:"required"`
	Errmsg string   `json:"errmsg" form:"errmsg" validate:"required"`
	Data   *Manager `json:"data,omitempty" form:"data"`
}

// NewGetManagerResp creates a new GetManagerResp instance
// and initializes fields with default values.
func NewGetManagerResp() *GetManagerResp {
	return &GetManagerResp{}
}

// DecodeJSON decodes a JSON object into GetManagerResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *GetManagerResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashErrno  = 0x9f713ddd75d2f3ab // HashKey("errno")
		hashErrmsg = 0xb91eb24f31be5e25 // HashKey("errmsg")
		hashData   = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasErrno  bool
		hasErrmsg bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashErrno:
			hasErrno = true
			if r.Errno, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}
		case hashErrmsg:
			hasErrmsg = true
			if r.Errmsg, err = jsonflow.DecodeString(d); err != nil {
				return err
			}
		case hashData:
			if r.Data, err = jsonflow.DecodeObject(NewManager)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasErrno {
		return errutil.Explain(err, "missing required field \"errno\"")
	}
	if !hasErrmsg {
		return errutil.Explain(err, "missing required field \"errmsg\"")
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *GetManagerResp) Validate() error {
	if !(OneOfErrCode(x.Errno)) {
		return errutil.Explain(nil, "validate failed on \"GetManagerResp.Errno\"")
	}
	return nil
}

type DeleteManagerResp struct {
	Errno  ErrCode `json:"errno" form:"errno" validate:"required"`
	Errmsg string  `json:"errmsg" form:"errmsg" validate:"required"`
	Data   *bool   `json:"data,omitempty" form:"data"`
}

// NewDeleteManagerResp creates a new DeleteManagerResp instance
// and initializes fields with default values.
func NewDeleteManagerResp() *DeleteManagerResp {
	return &DeleteManagerResp{}
}

// DecodeJSON decodes a JSON object into DeleteManagerResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *DeleteManagerResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashErrno  = 0x9f713ddd75d2f3ab // HashKey("errno")
		hashErrmsg = 0xb91eb24f31be5e25 // HashKey("errmsg")
		hashData   = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasErrno  bool
		hasErrmsg bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashErrno:
			hasErrno = true
			if r.Errno, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}
		case hashErrmsg:
			hasErrmsg = true
			if r.Errmsg, err = jsonflow.DecodeString(d); err != nil {
				return err
			}
		case hashData:
			if r.Data, err = jsonflow.DecodeBoolPtr(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasErrno {
		return errutil.Explain(err, "missing required field \"errno\"")
	}
	if !hasErrmsg {
		return errutil.Explain(err, "missing required field \"errmsg\"")
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *DeleteManagerResp) Validate() error {
	if !(OneOfErrCode(x.Errno)) {
		return errutil.Explain(nil, "validate failed on \"DeleteManagerResp.Errno\"")
	}
	return nil
}

// Paginated response
type ManagersPageData struct {
	Total *int64     `json:"total,omitempty" form:"total"`
	Page  *int64     `json:"page,omitempty" form:"page"`
	Size  *int64     `json:"size,omitempty" form:"size"`
	Items []*Manager `json:"items,omitempty" form:"items"`
}

// NewManagersPageData creates a new ManagersPageData instance
// and initializes fields with default values.
func NewManagersPageData() *ManagersPageData {
	return &ManagersPageData{}
}

// DecodeJSON decodes a JSON object into ManagersPageData using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *ManagersPageData) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashTotal = 0x2dcede7d543a4ffd // HashKey("total")
		hashPage  = 0x38b2a0deba58916  // HashKey("page")
		hashSize  = 0x4dea9618e618ae3c // HashKey("size")
		hashItems = 0x3e7884bf4f412c6f // HashKey("items")
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashTotal:
			if r.Total, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashPage:
			if r.Page, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashSize:
			if r.Size, err = jsonflow.DecodeIntPtr[int64](d); err != nil {
				return err
			}
		case hashItems:
			if r.Items, err = jsonflow.DecodeArray(jsonflow.DecodeObject(NewManager))(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}
	return
}

type ListManagersByPageResp struct {
	Errno  ErrCode           `json:"errno" form:"errno" validate:"required"`
	Errmsg string            `json:"errmsg" form:"errmsg" validate:"required"`
	Data   *ManagersPageData `json:"data,omitempty" form:"data"`
}

// NewListManagersByPageResp creates a new ListManagersByPageResp instance
// and initializes fields with default values.
func NewListManagersByPageResp() *ListManagersByPageResp {
	return &ListManagersByPageResp{}
}

// DecodeJSON decodes a JSON object into ListManagersByPageResp using a hash-based
// field dispatch mechanism for high-performance parsing.
func (r *ListManagersByPageResp) DecodeJSON(d jsonflow.Decoder) (err error) {
	const (
		hashErrno  = 0x9f713ddd75d2f3ab // HashKey("errno")
		hashErrmsg = 0xb91eb24f31be5e25 // HashKey("errmsg")
		hashData   = 0x855b556730a34a05 // HashKey("data")
	)

	var (
		hasErrno  bool
		hasErrmsg bool
	)

	if err = jsonflow.DecodeObjectBegin(d); err != nil {
		return err
	}

	for {
		if d.PeekKind() == '}' {
			break
		}

		var key string
		key, err = jsonflow.DecodeString(d)
		if err != nil {
			return err
		}

		switch hashutil.FNV1a64(key) {
		case hashErrno:
			hasErrno = true
			if r.Errno, err = jsonflow.DecodeInt[ErrCode](d); err != nil {
				return err
			}
		case hashErrmsg:
			hasErrmsg = true
			if r.Errmsg, err = jsonflow.DecodeString(d); err != nil {
				return err
			}
		case hashData:
			if r.Data, err = jsonflow.DecodeObject(NewManagersPageData)(d); err != nil {
				return err
			}
		default:
			if err = d.SkipValue(); err != nil {
				return err
			}
		}
	}

	if err = jsonflow.DecodeObjectEnd(d); err != nil {
		return err
	}

	if !hasErrno {
		return errutil.Explain(err, "missing required field \"errno\"")
	}
	if !hasErrmsg {
		return errutil.Explain(err, "missing required field \"errmsg\"")
	}
	return
}

// Validate checks field values using generated validation expressions.
func (x *ListManagersByPageResp) Validate() error {
	if !(OneOfErrCode(x.Errno)) {
		return errutil.Explain(nil, "validate failed on \"ListManagersByPageResp.Errno\"")
	}
	return nil
}
