// Code generated by gs-http-gen compiler. DO NOT EDIT.

package proto

import (
	"context"
	"net/http"

	"github.com/go-spring/stdlib/httpsvr"
)

// ManagerService defines the interface that service must implement.
type ManagerService interface {
	// Assistant ...
	Assistant(context.Context, *AssistantReq, chan<- *httpsvr.Event[*AssistantResp])
	// AssistantV2 ...
	AssistantV2(context.Context, *AssistantReq, chan<- *httpsvr.Event[string])
	// Create a new manager
	CreateManager(context.Context, *CreateManagerReq) *CreateManagerResp
	// Delete a manager
	DeleteManager(context.Context, *ManagerReq) *DeleteManagerResp
	// Get manager by ID
	GetManager(context.Context, *ManagerReq) *GetManagerResp
	// List managers with pagination
	ListManagersByPage(context.Context, *ListManagersByPageReq) *ListManagersByPageResp
	// Update manager info
	UpdateManager(context.Context, *UpdateManagerReq) map[string]any
}

// Routers returns a list of HTTP routers for the service.
func Routers(server ManagerService, fn httpsvr.NewRequestContext) []httpsvr.Router {
	return []httpsvr.Router{
		{
			Method:  "GET",
			Pattern: "/assistant",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleStream(w, r.WithContext(ctx), NewAssistantReq(), server.Assistant)
			},
		},
		{
			Method:  "GET",
			Pattern: "/assistantV2",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleStream(w, r.WithContext(ctx), NewAssistantReq(), server.AssistantV2)
			},
		},
		{
			Method:  "POST",
			Pattern: "/managers",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewCreateManagerReq(), server.CreateManager)
			},
		},
		{
			Method:  "DELETE",
			Pattern: "/managers/{id}",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewManagerReq(), server.DeleteManager)
			},
		},
		{
			Method:  "GET",
			Pattern: "/managers/{id}",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewManagerReq(), server.GetManager)
			},
		},
		{
			Method:  "GET",
			Pattern: "/managers/page",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewListManagersByPageReq(), server.ListManagersByPage)
			},
		},
		{
			Method:  "PUT",
			Pattern: "/managers/{id}",
			Handler: func(w http.ResponseWriter, r *http.Request) {
				ctx := httpsvr.WithRequestContext(r.Context(), fn(r, w))
				httpsvr.HandleJSON(w, r.WithContext(ctx), NewUpdateManagerReq(), server.UpdateManager)
			},
		},
	}
}
